# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e355247a-88e2-4e6e-8035-538398c6b091'
  imageRepository: 'projetointegradorencurtadorurl'
  containerRegistry: 'testshortnerurlcontainerregister.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (99d0fa6e-d94e-4d3a-a721-b0c4e260304c)'
        azureContainerRegistry: '{"loginServer":"testshortnerurlcontainerregister.azurecr.io", "id" : "/subscriptions/99d0fa6e-d94e-4d3a-a721-b0c4e260304c/resourceGroups/test-shortenerurl/providers/Microsoft.ContainerRegistry/registries/testshortnerurlcontainerregister"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (99d0fa6e-d94e-4d3a-a721-b0c4e260304c)'
        azureContainerRegistry: '{"loginServer":"testshortnerurlcontainerregister.azurecr.io", "id" : "/subscriptions/99d0fa6e-d94e-4d3a-a721-b0c4e260304c/resourceGroups/test-shortenerurl/providers/Microsoft.ContainerRegistry/registries/testshortnerurlcontainerregister"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
